### ISSUE TITLE
mongodb 例子

### ISSUE THREAD

**Issue by supersujj** [liukelin/canal_mysql_nosql_sync#4]
请问一下，能否提供一个同步到mongodb的例子，感谢！

**Comment by liukelin** [comment]
写了个，可以看下 这个例子[/python_sync_nosql/sync_mongo.py](https://github.com/liukelin/canal_mysql_nosql_sync/tree/master/python_sync_nosql)
DB和mongo表结构类似：
  db    => db
  table => 集合
  column=> coll

**Comment by supersujj** [comment]
谢谢！

**Comment by liukelin** [comment]
不客气，讨论进步
