### ISSUE TITLE
请问下canal是100%不丢消息的吗

### ISSUE THREAD

**Issue by yizhixiaotaozi** [liukelin/canal_mysql_nosql_sync#6]
如果canal突然挂了，或者有段时间没运行，增量是否会丢失

**Comment by liukelin** [comment]
参考MySQL从库机制，它会记录同步点(就是记录当前同步到binlog哪个文件哪一行位置)挂了再重启的话 会从这个位置继续同步。

**Comment by f-zhao** [comment]
可以看下canal的position保存机制，按照binlog的position保存的

**Comment by yizhixiaotaozi** [comment]
感谢
